[package]
name = "npack"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "ni"
path = "src/bin/ni.rs"

[dependencies]
cargo_metadata = "0.18.1"
serde = "1.0.193"
serde_json = "1.0.108"
